// Shaniah Nizzar Dec 7, 2022 - This is a pipeline for a Java Application

pipeline {
    agent any
    parameters {
        booleanParam(defaultValue: false, description:'Whether to Run the Code', name: 'RUN')
        string(defaultValue: 'Latest', description:'Name of build', name:'BUILD_NAME')
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo Starting Build...'
                sh 'mvn -B -DskipTests clean install'
                sh 'echo Build Complete.'
            }
        }

        stage('Code Quantity') {
            steps {
                sh 'cd src/main/java/com/mycompany/app && cat App.java | wc -l' 
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
            }
        
        stage('Run') {
            when { 
                expression { params.RUN }
            }
            steps {
                sh 'ls'
                sh "chmod +x deliver.sh && ./deliver.sh"
            }

        }

        stage('Build Results') {
            steps{
                sh 'echo Build ${BUILD_NAME} completed successfully'
                sh 'echo I have now completed ACIT 4850!'
                sh 'echo Student Number A01199153 and Group Number 4'
            }
        }
        }
    }
